### PR TITLE
Added custom name to APIObject

### PR DESCRIPTION
**Pull request by mohpor**
Signed-off-by: Mohammad Porooshani <porooshani@gmail.com>

### CODE REVIEW

**Comment by mczachurski** [comment]
Hi,

Feature is not completed. You need to add one more unit test (to `OpenAPIPathsBuilderTests.swift` file): 

```swift
    func testActionObjectResponseReferenceWithCustomNameShouldBeAddedToOpenAPIDocument() {

        // Arrange.
        let openAPIBuilder = OpenAPIBuilder(
            title: "Title",
            version: "1.0.0",
            description: "Description"
            )
            .add(APIController(name: "ControllerName", description: "ControllerDescription", actions: [
                APIAction(method: .get, route: "/animals", summary: "Action summary",
                          description: "Action description", responses: [
                            APIResponse(code: "200", description: "Response description", object: Animal.self)
                    ]
                )
            ]))
            .add([
                APIObject(object: Animal(name: "Dog", age: 21), customName: "CustomAnimal")
            ])

        // Act.
        let openAPIDocument = openAPIBuilder.built()

        // Assert.
        XCTAssertEqual("#/components/schemas/CustomAnimal", openAPIDocument.paths["/animals"]?.get?.responses?["200"]?.content?["application/json"]?.schema?.ref)
    }
```

You changed only one part of the JSON (part witch entities description). However entities names are also used as a links (references) in actions descriptions. See below:

```json
            "get": {
                "summary": "Returns all pets",
                "description": "Returns all pets from the system that the user has access to",
                "responses": {
                    "200": {
                        "description": "A list of pets.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                        "items": {
                                            "$ref": "#/components/schemas/CustomAnimal"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
```

That names must be the same. That will be the harder part ;-).

**Comment by mohpor** [comment]
Hmmmm, let me add your test and see what's happening.

**Comment by mohpor** [comment]
@mczachurski 
Well, that's fairly complicated. We have two options:
1. Add the custom name in `APIResponse` which I'm sure you agree is not good (1 custom name is bad enough already).
2. Change `APIResponse` so that it accepts `APIObject` instead of a `type`. Or at least provide an overload to accept such parameters and do whatever necessary with the custom name.

I prefer the second approach but I need your input before making further updates.

**Comment by mczachurski** [comment]
Yes it is a little bit complicated. We should have custom name in one place (in `APIObject`). And we shouldn't change any other public API. However during schama build (file: `OpenAPIBuilder.swift`):

```swift
        let openAPISchemasBuilder = OpenAPISchemasBuilder(objects: self.objects)
        let schemas = openAPISchemasBuilder.built()
```

we can build dictionary [orginalName: customName]. That dictionary should be used in next step:

```swift
        let openAPIPathsBuilder = OpenAPIPathsBuilder(controllers: self.controllers, authorizations: self.authorizations)
        let paths = openAPIPathsBuilder.built()
```

**Comment by mohpor** [comment]
That's a nice idea, I will try to do that.

**Comment by mohpor** [comment]
@mczachurski 
I have checked on the code beat issues, there are things I can do to improve codebeat's score but it makes your code look different. for example, about passing custom names, I can set default value for the dictionary and if custom name map is not empty, assign the map to the operation builder, but that's slightly different from the neat code you've provided.

Also: 
```swift 
func objectReference(for type: Any.Type) -> String {
        var mirrorObjectType = String(describing: type)
        mirrorObjectType = customSchemaNames[mirrorObjectType] ?? mirrorObjectType
        let objectTypeReference = "#/components/schemas/\(mirrorObjectType)"
        return objectTypeReference
    }
```

can be refactored.

**Pull request merged**
