### PR TITLE
Changed type name to fully identifiable path

### PR DESCRIPTION
**Pull request by mohpor**
Signed-off-by: Mohammad Porooshani <porooshani@gmail.com>

### CODE REVIEW

**Comment by eneko** [comment]
Code changes look good, however, at first glance, this might not be a good idea. API Spec models (those the API serves to the Internet) should probably be non-namespaced. In other words, internal name spacing should not be exposed by the API models, nor clients should be aware of it.

I've run some tests and the generated spec is valid (I updated the test models to have one required field):
```yaml
paths: {}
servers: []
openapi: 3.0.1
info:
  title: Title
  version: 1.0.0
  description: Description
tags: []
components:
  schemas:
    Base.Branch.StructItem:
      type: object
      properties:
        bar:
          type: string
          example: bar
      required:
        - bar
    Base.Branch.ClassItem:
      type: object
      properties:
        foo:
          type: string
          example: foo
      required:
        - foo
  securitySchemes: {}
```

Screenshot 2019-03-10 09 31 29

It does not feel good, however it works. I'd like to see if any other backend API's built in different languages expose namespaced models like this.

**Comment by eneko** [comment]
For reference, the generated models from Swagger Swift 4 generator would look like this:

```swift
public struct BaseBranchStructItem: Codable {


}

public struct BaseBranchClassItem: Codable {


}
```

The name is misleading, because the client uses structs for all models, but other than that, and the namespace "dots" being removed, it seems to work. 

Again, not 100% convinced this is a good idea.

**Comment by mohpor** [comment]
I know it seems kind of odd, that's why I proposed the custom name.

it can be optional and types can still be inferred.

so, what's it gonna be?

**Comment by eneko** [comment]
@mohpor my recommendation would be for you to write custom models for your API. These are commonly referenced as [Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object) (DTOs) and are used for API contracts, so the same DTO model can be used in the backend and client. You can then define custom initializers for your DTOs, so they can be initialized with one or more of your namespaced models. 

For example, given your code:
```swift
enum Base {
  enum Branch {
    class ClassItem {}
    struct StructItem {}
  }
}
```

You could create a DTO:
```swift
struct ClassItemDTO: Codable {
  init(classItem: Base.Branch.ClassItem) { ... }
}
```

This will ensure your API is clean, while you can use your namespaces internally within your backend application.

**Comment by mohpor** [comment]
@eneko Thanks for the hint. I'm familiar with DTOs and what I'm actually doing is something completely similar.

All I'm saying is that model name is something completely irrelevant to what the API's user should or will use, I like my pattern and I can stand by its rationale, and that's just one case. The goal of documenting API is not to force everybody to adhere to a specific pattern or use case.

I guess I've said (and done) enough, the rest is up to @mczachurski. he can close this PR if needed.

P.S:

I'm using Swiftgger to document some APIs I'm developing over Vapor.
The main idea behind my model design is to make it clearer for me, not API user. Therefore I have something like this:
```swift
enum Models {
  enum Transaction {
    enum List {
      class Request {}
      class Model {
        .... 
      func dto() -> DTO { ... }

     }
      class DTO {}
    }
  }
}
```

and then in my code I do something like this:

```swift
func list(_ req: Request) -> Future<Models.Transaction.List.DTO> {
 ...
req.future().map { $0.dto() }
}
```

I guess that clears my case, and I'm not insisting on its validity and I'm not trying to force anything on anyone, but I want to be able to document this API's schema to reflect the `List` as southing like `TransactionsList` or at least `Models.Transaction.List.DTO`

**Comment by mczachurski** [comment]
I think @eneko is right that you should expose in API documentation "business entities" (like User, Transaction, Bank etc.). From the perspective of a developer who will use this documentation it doesn't matter where you've put your entity. I also verified that in schema created by Swashbuckle.AspNetCore generator there is no information about namespaces at all (and .NET has better namespace support).

Thank you for your PR, however after longer thoughts I think your solution has two issues:

1. we shouldn't trust output from dump() method. If Apple changes that output a little bit then this code will fail. It will be better to check what dump() method do and try the same in our code.
2. if we introduce that change then other developers who use Swagger and have similar construction to yours will get class names with dots. And maybe they don't want to expose internal constructions.

Therefore I think maybe we can back to first idea with custom name as a (optional) string. We can create object description like that:

```swift
APIObject(object: UserDto(id: UUID(), name: "John Doe"), withCustomName: "User")
```

or in your case:

```swift
APIObject(object: Models.Transactions.Response.UserDto(id: UUID(), name: "John Doe"), withCustomName: "Models.Transactions.Response.UserDto")
```

What do you think guys?

**Comment by mohpor** [comment]
Both valid points. That was my original request. It would make much more sense. You can close this PR. I can make a new PR based on the new requirements tomorrow, if that's ok with you.

**Comment by eneko** [comment]
Agreed, having the option to provide a custom name makes Swiftgger more flexible. 

Thank you, both.

**Pull request closed without merging**
